name: Cypress Tests on Live URL

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        record: true
        key: ${{ secrets.CYPRESS_RECORD_KEY }}
        config: baseUrl=https://rahulshettyacademy.com/seleniumPractise/#/
